name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://danchoicloud.hoangndst.com

    steps:
      - name: Deploy
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}?tag=${{ github.ref_name }}
          verify_ssl: false
